CREATE SCHEMA HUB_FISCAL_OWNER;

CREATE DOMAIN CLOB as text;

CREATE TABLE HUB_FISCAL_OWNER.VENDA_TESTE
(
    ID                       NUMERIC(38, 0) NOT NULL,
    CANAL                    VARCHAR(100) NOT NULL,
    CODIGO_EMPRESA           INTEGER       NOT NULL,
    CODIGO_LOJA              INTEGER       NOT NULL,
    NUMERO_PDV               INTEGER       NOT NULL,
    NUMERO_PEDIDO            VARCHAR(38)  NOT NULL,
    NUMERO_ORDEM_EXTERNO     VARCHAR(38)  NOT NULL,
    VALOR_TOTAL              NUMERIC(38, 2) NOT NULL,
    QTD_ITEM                 NUMERIC(38,0)  NOT NULL,
    VENDA_REQUEST            JSONB           NOT NULL,
    DATA_ATUALIZACAO         TIMESTAMP     NOT NULL,
    DATA_REQUISICAO          TIMESTAMP     NOT NULL,
    CHAVE_NFE                VARCHAR(44),
    NUMERO_NOTA              NUMERIC(38,0),
    DATA_EMISSAO             TIMESTAMP,
    PDF                      CLOB,
    SITUACAO                 VARCHAR(100) NOT NULL,
    MOTIVO                   VARCHAR(255),
    CONSTRAINT PK_VENDA PRIMARY KEY (ID)
);

CREATE SEQUENCE HUB_FISCAL_OWNER.VENDA_TESTE_SEQ MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 20;